notifications:
  email:
  - apple.builds@sagebase.org
language: objective-c
osx_image: xcode12.4
xcode_workspace: Research.xcworkspace
xcode_scheme: RSDCatalog
cache:
  - bundler
  - cocoapods
addons:
  homebrew:
    packages: python3
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - pip3 install virtualenv
  - virtualenv -p python3 ~/venv
  - source ~/venv/bin/activate
install:
  - pip install travis-wait-improved
  - gem install bundler
  - bundle install
script:
  - travis-wait-improved --timeout 30 ./travis/build.sh
branches:
  only:
  - master
  - "/^stable-.*$/"
